apiVersion: v1
kind: Service
metadata:
  name: chatapp-srv
spec:
  type: NodePort
  selector: 
    app: chatapp
  ports:
    - name: chatapp
      protocol: TCP
      port: 3000
      targetPort: 3000
