apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp
          image: devassumpcao/chatapp:latest
          ports:
            - containerPort: 3000
              protocol: TCP